name: pyext-a
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run test docker
      working-directory: ./pyext/part-a
      run: docker build -f Dockerfile.test .
